# Configuración de la base de datos
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/serviciosYA?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
# Configuración de Spring Data JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  # Configuración de Thymeleaf
  thymeleaf:
    cache: false

server:
  port: 8080